language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t tested_image .
  - docker run --detach --name tested_image tested_image

script:
  - docker ps | grep -q tested_image
  - docker inspect tested_image
  - docker inspect tested_image | grep -i 'networksettings'
  - docker stop tested_image

notifications:
  webhooks: https://hooks.microbadger.com/images/ernestasposkus/centos7/ekwcaS9-LqH7M44Z3zaLbmFRPFI=
